@startuml
actor プレイヤー
left to right direction
rectangle {
    プレイヤー -- (ゲームを始める)
    プレイヤー -- (盤面を見る)
    プレイヤー -- (コマを置く)
    プレイヤー -- (スキップする)
    プレイヤー -- (ヘルプを見る)
    プレイヤー -- (一時中断する)
    プレイヤー -- (完全終了する)
}
@enduml