name: 不具合報告(Bug report)
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: 概要
      description: 発生したバグについて教えてください(A description of what the bug is)
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        以下、オプションです。よろしければご記入ください。
  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: バグの再現方法を教えてください(Steps to reproduce the behavior)
      value: |
        1.
        2.
        3.
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待した動作
      description: その機能がするべきはずの動作を教えてください(A description of what you expected to happen)
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: 実行していたゲームモードを教えてください
      options:
        - ローカル対戦モード
        - ボット対戦モード
        - 観戦モード
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: 使用したブラウザを教えてください(What browsers are you seeing the problem on?)
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: 関連するログの出力をコピーしてペーストしてください。 これは自動的にコードにフォーマットされるので、バックティックは不要です。
      render: shell
  - type: textarea
    id: other
    attributes:
      label: その他(other)
